# Generated by Django 4.2.1 on 2023-06-07 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmodel',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='chat_files/'),
        ),
        migrations.AddField(
            model_name='chatmodel',
            name='file_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
